# Generated by Django 5.2.8 on 2025-11-20 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_promocion_nombre_promocion_url_imagen'),
        ('Caja', '0002_remove_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='Admin.pedido'),
        ),
    ]
