# Generated by Django 5.2.8 on 2025-11-23 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0003_alter_venta_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='Caja.empleado'),
        ),
    ]
