// <auto-generated />
using System;
using Cafeteria_back.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cafeteria_back.Migrations
{
    [DbContext(typeof(MiDbContext))]
    partial class MiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cafeteria_back.Entities.Extras.Extra", b =>
                {
                    b.Property<long>("Id_extra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_extra"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float?>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Id_extra");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Pedidos.Pedido", b =>
                {
                    b.Property<long>("Id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_pedido"));

                    b.Property<long>("Cliente_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Tipo_Entrega")
                        .HasColumnType("integer");

                    b.Property<float?>("Total_descuento")
                        .HasColumnType("real");

                    b.Property<float?>("Total_estimado")
                        .HasColumnType("real");

                    b.Property<int?>("estado")
                        .HasColumnType("integer");

                    b.HasKey("Id_pedido");

                    b.HasIndex("Cliente_id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Productos.Producto", b =>
                {
                    b.Property<long>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_producto"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Nombre_")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Image_url")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<string>("Sabores")
                        .HasColumnType("text");

                    b.Property<string>("Sub_categoria")
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.HasKey("Id_producto");

                    b.ToTable("Producto", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Promociones.Promocion", b =>
                {
                    b.Property<long>("Id_promocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_promocion"));

                    b.Property<string>("Nombre_")
                        .HasColumnType("text");

                    b.Property<float>("Descuento")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fech_ini")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_final")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Strategykey")
                        .HasColumnType("text");

                    b.HasKey("Id_promocion");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Detalle_extra", b =>
                {
                    b.Property<long>("Detalle_pedido_id")
                        .HasColumnType("bigint");

                    b.Property<long>("Extra_id")
                        .HasColumnType("bigint");

                    b.HasKey("Detalle_pedido_id", "Extra_id");

                    b.HasIndex("Extra_id");

                    b.ToTable("DetalleExtra");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Detalle_pedido", b =>
                {
                    b.Property<long>("Id_detalle_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_detalle_pedido"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<long>("Pedido_id")
                        .HasColumnType("bigint");

                    b.Property<float?>("Precio_unitario")
                        .HasColumnType("real");

                    b.Property<long>("Producto_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id_detalle_pedido");

                    b.HasIndex("Pedido_id");

                    b.HasIndex("Producto_id");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Producto_Promocion", b =>
                {
                    b.Property<long>("Producto_id")
                        .HasColumnType("bigint");

                    b.Property<long>("Promocion_id")
                        .HasColumnType("bigint");

                    b.HasKey("Producto_id", "Promocion_id");

                    b.HasIndex("Promocion_id");

                    b.ToTable("ProductopPromocion");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Usuarios.Cliente", b =>
                {
                    b.Property<long>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_user"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("text");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("Nit")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.Property<string>("Usuari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_user");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Usuarios.Empleado", b =>
                {
                    b.Property<long>("Id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_user"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaContrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .HasColumnType("text");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.Property<string>("Usuari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_user");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Ventas.Venta", b =>
                {
                    b.Property<long>("Id_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_venta"));

                    b.Property<long>("Empleado_id")
                        .HasColumnType("bigint");

                    b.Property<long>("Pedido_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo_de_Pago")
                        .HasColumnType("text");

                    b.Property<float>("Total_final")
                        .HasColumnType("real");

                    b.Property<DateTime>("Ven_fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id_venta");

                    b.HasIndex("Empleado_id");

                    b.HasIndex("Pedido_id")
                        .IsUnique();

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Productos.Bebida", b =>
                {
                    b.HasBaseType("Cafeteria_back.Entities.Productos.Producto");

                    b.Property<string>("Tamanio")
                        .HasColumnType("text");

                    b.ToTable("Bebida", (string)null);
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Productos.Comida", b =>
                {
                    b.HasBaseType("Cafeteria_back.Entities.Productos.Producto");

                    b.Property<string>("Proporcion")
                        .HasColumnType("text");

                    b.ToTable("Comida", (string)null);
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Pedidos.Pedido", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Usuarios.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Detalle_extra", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Tablas_intermedias.Detalle_pedido", "Detalle_pedido")
                        .WithMany("Detalle_extras")
                        .HasForeignKey("Detalle_pedido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cafeteria_back.Entities.Extras.Extra", "Extra")
                        .WithMany("Detalle_extra")
                        .HasForeignKey("Extra_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalle_pedido");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Detalle_pedido", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Pedidos.Pedido", "Pedido")
                        .WithMany("Detalle_pedido")
                        .HasForeignKey("Pedido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cafeteria_back.Entities.Productos.Producto", "Producto")
                        .WithMany("Detalle_pedido")
                        .HasForeignKey("Producto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Producto_Promocion", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Productos.Producto", "Producto")
                        .WithMany("Producto_promocion")
                        .HasForeignKey("Producto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cafeteria_back.Entities.Promociones.Promocion", "Promocion")
                        .WithMany("Producto_promocion")
                        .HasForeignKey("Promocion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Ventas.Venta", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Usuarios.Empleado", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("Empleado_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cafeteria_back.Entities.Pedidos.Pedido", "Pedido")
                        .WithOne("Venta")
                        .HasForeignKey("Cafeteria_back.Entities.Ventas.Venta", "Pedido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Productos.Bebida", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Productos.Producto", null)
                        .WithOne()
                        .HasForeignKey("Cafeteria_back.Entities.Productos.Bebida", "Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Productos.Comida", b =>
                {
                    b.HasOne("Cafeteria_back.Entities.Productos.Producto", null)
                        .WithOne()
                        .HasForeignKey("Cafeteria_back.Entities.Productos.Comida", "Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Extras.Extra", b =>
                {
                    b.Navigation("Detalle_extra");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Pedidos.Pedido", b =>
                {
                    b.Navigation("Detalle_pedido");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Productos.Producto", b =>
                {
                    b.Navigation("Detalle_pedido");

                    b.Navigation("Producto_promocion");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Promociones.Promocion", b =>
                {
                    b.Navigation("Producto_promocion");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Tablas_intermedias.Detalle_pedido", b =>
                {
                    b.Navigation("Detalle_extras");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Usuarios.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Cafeteria_back.Entities.Usuarios.Empleado", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
