# Generated by Django 5.2.5 on 2025-08-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('sabores', models.CharField(max_length=100)),
                ('imagen_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.producto')),
                ('proporcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.producto')),
                ('tamaño', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.FloatField()),
                ('fecha_ini', models.DateField()),
                ('fech_final', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('producto', models.ManyToManyField(related_name='promociones', to='Admin.producto')),
            ],
        ),
    ]
