# Generated by Django 5.2.8 on 2025-11-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Cliente', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto',
            field=models.ManyToManyField(related_name='promociones', to='Admin.producto'),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_groups', related_query_name='usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_permissions', related_query_name='usuario', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
