# Generated by Django 5.2.8 on 2025-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_pedido_estado_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promocion',
            name='url_imagen',
            field=models.CharField(default='', max_length=100),
        ),
    ]
