# Generated by Django 5.2.8 on 2025-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('recoger', 'Recoger en tienda'), ('domicilio', 'A Domicilio'), ('llevar', 'Para Llevar')], default='recoger', max_length=20),
        ),
    ]
