# Generated by Django 5.2.8 on 2025-11-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('recoger', 'Recoger en tienda'), ('domicilio', 'A Domicilio'), ('Llevar', 'Para Llevar'), ('delivery', 'Delivery')], default='recoger', max_length=20),
        ),
    ]
