# Generated by Django 5.2.8 on 2025-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('recoger', 'Recoger en tienda'), ('domicilio', 'A Domicilio'), ('Llevar', 'Para Llevar'), ('Delivery', 'delivery')], default='recoger', max_length=20),
        ),
    ]
