# Generated by Django 5.2.8 on 2025-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
    ]
