# Generated by Django 5.2.8 on 2025-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_promocion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Promociones/'),
        ),
    ]
