# Generated by Django 5.2.8 on 2025-11-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_producto_imagen'),
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='detalle_pedido',
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='extras',
            field=models.ManyToManyField(related_name='detalles_de_pedido', to='Cliente.extra'),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='Admin.pedido'),
        ),
    ]
