# Generated by Django 5.2.7 on 2025-10-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apell_paterno',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
