# Generated by Django 5.2.7 on 2025-10-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_cliente_apell_paterno_cliente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apell_paterno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
