# Generated by Django 5.2.7 on 2025-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_remove_cliente_apell_paterno_remove_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
