# Generated by Django 5.2.8 on 2025-11-20 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_alter_pedido_cliente'),
        ('Caja', '0003_alter_venta_pedido'),
        ('Cliente', '0002_remove_extra_detalle_pedido_detalle_pedido_extras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='Admin.cliente')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='Caja.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Carrito.carrito')),
                ('extras', models.ManyToManyField(blank=True, to='Cliente.extra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', False), ('empleado__isnull', True)), models.Q(('cliente__isnull', True), ('empleado__isnull', False)), models.Q(('cliente__isnull', True), ('empleado__isnull', True)), _connector='OR'), name='un_solo_dueno_carrito'),
        ),
    ]
