# Generated by Django 5.2.8 on 2025-12-01 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_pedido_tipo_entrega'),
        ('Caja', '0004_alter_venta_empleado'),
        ('Carrito', '0002_alter_carrito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to='Admin.cliente'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos_atendidos', to='Caja.empleado'),
        ),
    ]
