# Generated by Django 5.2.8 on 2025-12-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0003_alter_carrito_cliente_alter_carrito_empleado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carrito',
            name='un_solo_dueno_carrito',
        ),
    ]
