# Generated by Django 5.2.8 on 2025-11-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
    ]
