# Generated by Django 5.2.8 on 2025-12-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('recoger', 'Recoger en tienda'), ('domicilio', 'A Domicilio'), ('Llevar', 'Para Llevar'), ('Delivery', 'delivery'), ('Mesa', 'mesa')], default='recoger', max_length=20),
        ),
    ]
