# Generated by Django 5.2.8 on 2025-12-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('recoger', 'Recoger en tienda'), ('domicilio', 'A Domicilio'), ('llevar', 'Para Llevar'), ('Delivery', 'delivery'), ('mesa', 'En Mesa')], default='recoger', max_length=20),
        ),
    ]
