# Generated by Django 5.2.8 on 2025-12-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('En_espera', 'En espera'), ('Preparando', 'Preparando'), ('Listo', 'Listo'), ('Entregado', 'Entregado'), ('Delivery', 'En Delivery')], default='pendiente', max_length=20),
        ),
    ]
